name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS 2 Humble
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt update
          sudo apt install -y ros-humble-desktop
          source /opt/ros/humble/setup.bash

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install ROS 2 dependencies
        run: |
          sudo apt update
          sudo apt install -y ros-humble-py-trees ros-humble-py-trees-ros

      - name: Run Tests
        run: python -m unittest discover tests
